-- Namespaces
USE ROLE ROLE_HERE;
USE DATABASE DATABASE_HERE;
USE SCHEMA SCHEMA_HERE;


COPY INTO @STAGE.DEV_DATA_OUTBOUND_FLEETASSIGNER/yyyy=", full_year, "/mm=",
full_month, "/dd=", full_day, "/fleet_assigner", ".csv 
FROM (SELECT * FROM DATAENG_TEST.EXTRACT.SUPPLIER_4_PERCENT) 
STORAGE_INTEGRATION = EXTRACT
FILE_FORMAT = ( TYPE = CSV null_if=('') COMPRESSION = None) 
OVERWRITE = TRUE 
SINGLE = TRUE 
HEADER = TRUE;